---
- hosts: all
  become: true
  tasks:
    - name: Update package list
      become: yes
      apt:
        update_cache: yes

    - name: Install required packages
      become: yes
      apt:
        name:
          - ca-certificates
          - curl
          - net-tools
          - apt-transport-https
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - gnupg-agent
          - autoconf
          - dpkg-dev
          - file
          - g++
          - gcc
          - libc-dev
          - make
          - pkg-config
          - re2c
          - wget

    - name: Create /etc/apt/keyrings directory
      become: yes
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download and install Docker GPG keyring
      become: yes
      shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg"

    - name: Add Repo
      ansible.builtin.apt_repository:
        filename: docker.gpg
        repo: "deb [arch={{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Update package
      become: yes
      apt:
        update_cache: yes

    - name: Install docker
      ansible.builtin.apt:
        name: ["docker-ce", "docker-ce-cli", "containerd.io"]
        state: latest
        update_cache: true

    - name: Install docker-compose from official github repo
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: "u+x,g+x"

    - name: Install Docker Module for Python
      ansible.builtin.pip:
        name: docker
